---
name: localize

on:
  push:
    branches: [master]
    paths:  # prevents workflow from running unless these files change
      - '.github/workflows/localize.yml'
      - 'locale/themerr-kodi.po'
      - 'src/**.py'
  workflow_dispatch:

jobs:
  localize:
    name: Update Localization
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Set up Python Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements-dev.txt

      - name: Update Strings
        run: |
          python -m scripts.locale --extract

      - name: git diff
        run: |
          # disable the pager
          git config --global pager.diff false

          # print the git diff
          git diff locale/themerr-kodi.po

          # set the variable with minimal output, replacing `\t` with ` `
          OUTPUT=$(git diff --numstat locale/themerr-kodi.po | sed -e "s#\t# #g")
          echo "git_diff=${OUTPUT}" >> $GITHUB_ENV

      - name: git reset
        if: ${{ env.git_diff == '1 1 locale/themerr-kodi.po' }}  # only run if more than 1 line changed
        run: |
          git reset --hard

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create/Update Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            locale/*.po
          token: ${{ secrets.GH_BOT_TOKEN }}  # must trigger PR tests
          commit-message: New localization template
          branch: localize/update
          delete-branch: true
          base: master
          title: New Babel Updates
          body: |
            Update report
            - Updated ${{ steps.date.outputs.date }}
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            babel
            l10n
